version: "3.9"
services:
  app:
    depends_on:
      - db
    image: q1eap/app
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["npm", "test"]

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME:?}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
