version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
    command: ["npm", "start"]
    volumes:
      - ./app:/app

  caddy:
    image: caddy:2.4.3-alpine
    ports:
      - 80:80
      - 443:443
      - 8080:80
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
    depends_on:
      - app
