version: "3.9"
services:
  app:
    depends_on:
      - db
    image: q1eap/app
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["make", "test"]

  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME:?}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
