version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["make", "start"]
    volumes:
      - ./app:/app

  caddy:
    image: caddy:2.4.3-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - "$PWD/services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "$PWD/app:/etc/caddy/app"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
