version: "3.9"
services:
  app:
    depends_on:
      - db
    image: q1eap/app
    build:
      context: .
      dockerfile: Dockerfile.production
    command: ["npm", "test"]

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
